# .render.yaml
services:
  - type: web
    name: rust-message-server
    env: rust
    plan: free
    repo: https://github.com/traitimtrongvag/MessageAnonymous.git
    branch: main
    buildCommand: cargo build --release
    startCommand: ./target/release/message server --listen 0.0.0.0:$PORT
    envVars:
      - key: PORT
        fromRender: PORT
