services:
  - type: web
    name: mesa-server
    env: rust
    plan: free
    repo: https://github.com/traitimtrongvag/Mesa.git
    branch: main
    buildCommand: cargo build --release
    startCommand: ./target/release/server
    envVars:
      - key: PORT
        fromRender: PORT
